"""Build the spectral weighting tables in assets/js/glazing-data.js.

    python _scripts/build_glazing_weights.py <folder with source CSVs>

Sources (download into the folder first):
  ASTMG173.csv               ASTM G173-03 reference spectra (NREL, via pvlib-python data); 'direct' column
                             = direct + circumsolar AM1.5, the solar weighting used for glazing (ISO 9050 / NFRC 300 style)
  CIE_std_illum_D65.csv      CIE standard illuminant D65, 1 nm (doi:10.25039/CIE.DS.hjfjmt59)
  CIE_sle_photopic.csv       CIE photopic luminous efficiency V(λ), 1 nm
  CIE_xyz_1931_2deg.csv      CIE 1931 2° colour-matching functions, 1 nm
Each table is integrated into 5 nm bins centred on 300, 305, …, 2500 nm and normalized.
"""
import csv, json, os, sys

src = sys.argv[1]
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def read(name, skip=0):
    rows = []
    with open(os.path.join(src, name), encoding='utf-8-sig') as f:
        for r in csv.reader(f):
            try: rows.append([float(x) for x in r if x.strip() != ''])
            except ValueError: continue
    return rows

def interp(xs, ys, x):
    if x <= xs[0]: return ys[0] if x == xs[0] else 0.0
    if x >= xs[-1]: return ys[-1] if x == xs[-1] else 0.0
    lo, hi = 0, len(xs) - 1
    while hi - lo > 1:
        mid = (lo + hi) // 2
        if xs[mid] <= x: lo = mid
        else: hi = mid
    t = (x - xs[lo]) / (xs[hi] - xs[lo])
    return ys[lo] + t * (ys[hi] - ys[lo])

GRID = list(range(300, 2501, 5))
def binned(fn):
    # integrate fn over [λ−2.5, λ+2.5) with 0.25 nm steps
    out = []
    for c in GRID:
        s = 0.0
        x = c - 2.5 + 0.125
        while x < c + 2.5:
            s += fn(x) * 0.25
            x += 0.25
        out.append(s)
    return out

g = read('ASTMG173.csv')
gx = [r[0] for r in g]; gd = [r[3] for r in g]
solar = binned(lambda x: interp(gx, gd, x))

d65 = read('CIE_std_illum_D65.csv'); dx = [r[0] for r in d65]; dy = [r[1] for r in d65]
v = read('CIE_sle_photopic.csv'); vx = [r[0] for r in v]; vy = [r[1] for r in v]
cmf = read('CIE_xyz_1931_2deg.csv'); cx = [r[0] for r in cmf]
D = lambda x: interp(dx, dy, x) if 380 <= x <= 780 else 0.0
vis = binned(lambda x: D(x) * interp(vx, vy, x))
X = binned(lambda x: D(x) * interp(cx, [r[1] for r in cmf], x))
Y = binned(lambda x: D(x) * interp(cx, [r[2] for r in cmf], x))
Z = binned(lambda x: D(x) * interp(cx, [r[3] for r in cmf], x))

def norm(a): s = sum(a); return [x / s for x in a]
def trim(a, sig=6): return [float('%.*g' % (sig, x)) for x in a]
ky = sum(Y)
data = {
    'grid': {'start': 300, 'step': 5, 'n': len(GRID)},
    'solar': trim(norm(solar)),
    'vis': trim(norm(vis)),
    'X': trim([x / ky for x in X]), 'Y': trim([x / ky for x in Y]), 'Z': trim([x / ky for x in Z])
}
js = ('/* Spectral weighting tables for the glazing calculator, generated by _scripts/build_glazing_weights.py.\n'
      '   Solar: ASTM G173-03 direct + circumsolar (AM1.5), 300–2500 nm. Visible: CIE D65 × V(λ), 380–780 nm.\n'
      '   Color: CIE D65 × CIE 1931 2° colour-matching functions, normalized so Y(white) = 1. 5 nm bins. */\n'
      'window.GlazingWeights = ' + json.dumps(data, separators=(',', ':')) + ';\n')
open(os.path.join(ROOT, 'assets', 'js', 'glazing-weights.js'), 'w', encoding='utf-8').write(js)
print('wrote glazing-weights.js: %d points, %.1f kB' % (len(GRID), len(js) / 1024))
print('solar fraction 380–780 nm: %.3f' % sum(w for l, w in zip(GRID, norm(solar)) if 380 <= l <= 780))
