"""Write the public resume page from the private, multi-version resume source.

    python _scripts/resume_public.py

The source, applications/resume-source.html, is git-ignored and holds every tailored version
(elements tagged data-v="master mfg rd inspect"). This script copies it to resume/index.html with
only the master version: every element whose data-v list lacks "master" is removed, and the
version switch is fixed to master. Tailored text therefore never reaches the public site.
Run by _scripts/build-resume.ps1; edit the source, not resume/index.html.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'applications', 'resume-source.html')
OUT = os.path.join(ROOT, 'resume', 'index.html')


def element_end(s, start, tag):
    """Index just past the end tag that closes the <tag> opened at `start` (nesting-aware)."""
    depth, i = 0, start
    pat = re.compile(r'<(/?)%s\b[^>]*>' % re.escape(tag), re.I)
    for m in pat.finditer(s, start):
        depth += -1 if m.group(1) else 1
        if depth == 0:
            return m.end()
    raise ValueError('unclosed <%s> at %d' % (tag, start))


def master_only(s):
    opener = re.compile(r'<([a-zA-Z][\w-]*)\b[^>]*\bdata-v="([^"]*)"[^>]*>')
    pos = 0
    while True:
        m = opener.search(s, pos)
        if not m:
            return s
        if 'master' in m.group(2).split():
            pos = m.end()
            continue
        a, b = m.start(), element_end(s, m.start(), m.group(1))
        line_start = s.rfind('\n', 0, a) + 1                      # take the whole line when the element sits alone on it
        if not s[line_start:a].strip() and s[b:b + 1] == '\n':
            a, b = line_start, b + 1
        s = s[:a] + s[b:]
        pos = a


src = open(SRC, encoding='utf-8').read()
out = master_only(src)
fixes = [
    (re.compile(r"var v = new URLSearchParams\(location\.search\)\.get\('v'\) \|\| 'master';\s*\n\s*if \(!/\^\(master\|mfg\|rd\|inspect\)\$/\.test\(v\)\) v = 'master';"),
     "var v = 'master';"),
    (re.compile(r"// Variant: \?v=master \(default\) \| mfg \| rd \| inspect\. Elements with data-v=\"a b\" show only in those variants\."),
     "// Public resume: master version only (generated by _scripts/resume_public.py)."),
    (re.compile(r"\n\s*// The phone number is never stored.*?\n\s*\}\n", re.S), "\n"),
    (re.compile(r'\n[ \t]*html\[data-v="mfg"\][^\n]*\n[ \t]*html\[data-v="rd"\][^\n]*\n[ \t]*html\[data-v="inspect"\][^\n]*'), ''),
]
for pat, rep in fixes:
    out, n = pat.subn(rep, out, count=1)
    if not n:
        sys.exit('resume_public.py: expected pattern not found: ' + pat.pattern[:60])
leftover = [v for v in re.findall(r'data-v="([^"]*)"', out) if 'master' not in v.split()]
if leftover:
    sys.exit('resume_public.py: non-master elements remain: %s' % leftover[:5])
open(OUT, 'w', encoding='utf-8').write(out)
print('resume/index.html: master version only (%d -> %d characters)' % (len(src), len(out)))
